import { defineField, defineType } from 'sanity'

export const destinationType = defineType({
  name: 'destination',
  title: 'Destination (country)',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Country name',
      type: 'string',
      description: 'e.g. "Uganda" or "Rwanda" or "Kenya"',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name', maxLength: 96 },
      description: 'e.g. "uganda" — auto-generated from the country name. Click Generate.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero title (H1)',
      type: 'text',
      rows: 2,
      description: 'e.g. "Uganda — The Pearl of Africa" — the main heading shown on the destination hero. Can span two lines.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero subtitle',
      type: 'text',
      rows: 3,
      description: 'e.g. "Home to half the world\'s mountain gorillas and one of Africa\'s richest primate ecosystems." — shown below the hero heading.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'mediaImage',
      description: 'Full-screen landscape photo for the destination hero. Use a high-resolution image (1920px wide or larger).',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'exploreIntro',
      title: 'Explore intro',
      type: 'text',
      rows: 4,
      description: 'e.g. "From the mist-draped rainforests of Bwindi to the vast savannahs of Queen Elizabeth..." — introductory paragraph shown at the top of the Explore section.',
    }),
    defineField({
      name: 'parkSummary',
      title: 'Park summary',
      type: 'text',
      rows: 4,
      description: 'e.g. "Uganda\'s ten national parks span six distinct ecosystems — from montane rainforest to open savannah." — paragraph shown in the National Parks summary section.',
    }),
    defineField({
      name: 'parkSummaryImage',
      title: 'Park summary image',
      type: 'mediaImage',
      description: 'Supporting image shown alongside the park summary text.',
    }),
    defineField({
      name: 'parks',
      title: 'National parks',
      type: 'array',
      of: [{ type: 'park' }],
      description: 'Add each national park featured on this destination page. The park slug is used in the detail page URL (e.g. /destinations/uganda/bwindi).',
    }),
    defineField({
      name: 'privilegedAccess',
      title: 'Privileged access experiences',
      type: 'array',
      of: [{ type: 'privilegedAccess' }],
      description: 'Unique access experiences not available to the general public — e.g. gorilla habituation, behind-the-scenes conservation visits.',
    }),
    defineField({
      name: 'lodges',
      title: 'Curated lodges',
      type: 'array',
      of: [{ type: 'lodge' }],
      description: 'Hand-selected lodges featured in the Curated Luxury Lodges section of the destination page. Add 4–8 lodges.',
    }),
    defineField({
      name: 'travelStats',
      title: 'Travel stats bar',
      type: 'travelStats',
      description: 'Four quick-reference stats displayed in the at-a-glance bar below the hero — best time, duration, key wildlife, travel style.',
    }),
    defineField({
      name: 'whyVisit',
      title: 'Why Visit section',
      type: 'whyVisit',
      description: 'Section 01 — a compelling case for visiting this destination: intro paragraph, 4–6 bullet points, and 3–5 stat numbers.',
    }),
    defineField({
      name: 'seasons',
      title: 'When to Go (seasons)',
      type: 'array',
      of: [{ type: 'season' }],
      description: 'Section 02 — add 2–4 seasonal entries (e.g. Dry Season, Green Season) explaining the best time to visit.',
    }),
    defineField({
      name: 'specialistQuote',
      title: 'Specialist quote',
      type: 'specialistQuote',
      description: 'A pull-quote from one of our travel designers — shown as a full-bleed quote block between the park sections.',
    }),
    defineField({
      name: 'conservation',
      title: 'Conservation & Impact section',
      type: 'conservation',
      description: 'Section 08 — conservation story, impact stats and partner organisations for this destination.',
    }),
    defineField({
      name: 'countryFaqs',
      title: 'Country FAQs',
      type: 'array',
      of: [{ type: 'countryFaq' }],
      description: 'Section 09 — add 5–8 frequently asked questions about travelling to this destination.',
    }),
    defineField({
      name: 'seoKeywords',
      title: 'SEO keywords',
      type: 'text',
      rows: 2,
      description: 'e.g. "Uganda safari, gorilla trekking Uganda, Bwindi Impenetrable Forest safari, Uganda wildlife" — comma-separated keywords for search engines.',
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort order',
      type: 'number',
      initialValue: 0,
      description: 'e.g. 1 for Uganda, 2 for Rwanda, 3 for Kenya — lower numbers appear first in listings.',
    }),
  ],
  orderings: [
    {
      title: 'Sort order',
      name: 'sortOrder',
      by: [
        { field: 'sortOrder', direction: 'asc' },
        { field: 'name', direction: 'asc' },
      ],
    },
  ],
  preview: {
    select: { title: 'name', media: 'heroImage.asset' },
  },
})
