export const site = {
  name: 'Still Wild Safaris',
  tagline: 'Bespoke luxury safaris in Uganda, Rwanda and Kenya',
  email: 'info@stillwildsafaris.com',
  partnersEmail: 'partners@stillwildsafaris.com',
  phone: '+256 769 797 796',
  phoneAlt: '+256 705 527 599',
  whatsapp: '+256 779 378 628',
  whatsappHref: 'https://wa.me/256779378628',
  instagram: 'https://www.instagram.com/stillwildsafaris?igsh=dmphN3Q0OTJyc214',
  facebook: 'https://www.facebook.com/share/18ZKkFXWb2/',
  youtube: 'http://www.youtube.com/@stillwildsafaris',
  address: 'Baskerville Ave, Kampala, Uganda',
  mapsQuery: 'Still+Wild+Safaris,+Baskerville+Ave,+Kampala',
} as const
